---
kind: pipeline
name: info

steps:
 - name: prepare
   image: maven:3-jdk-8
   commands:
   - mvn --version
   - java -version
   
trigger:
  branch:
  - master
  event:
  - push


---
kind: pipeline
name: build

steps:
 - name: test
   image: maven:3-jdk-8
   commands:
   - mvn test -B
   - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

trigger:
  status:
  - success

depends_on:
- info
