---
kind: pipeline
name: info

wechat:
  image: clem109/drone-wechat
  corpid: corpid
  corp_secret: secret
  agent_id: 1234567
  title: ${DRONE_REPO_NAME}
  description: "Build Number: ${DRONE_BUILD_NUMBER} failed. ${DRONE_COMMIT_AUTHOR} please fix. Check the results here: ${DRONE_BUILD_LINK} "
  msg_url: ${DRONE_BUILD_LINK}
  btn_txt: btn
  when:
    status: [ failure ]
    
steps:
- name: prepare
 image: maven:3-jdk-8
 commands:
 - mvn --version
 - java -version
   
- name: wechat
  image: lizheming/drone-wechat
  settings:
    corpid: 
      from_secret: wechat_corpid
    corp_secret:
      from_secret: wechat_corp_secret
    agent_id: 
      from_secret: agent_id
    to_user: 111
    to_party: 112
    to_tag: ${DRONE_REPO_NAME}
    msg_url: ${DRONE_BUILD_LINK}
    safe: 1
    btn_txt: more
    title: ${DRONE_REPO_NAME}
    message: >
      {%if success %}
        build {{build.number}} succeeded. Good job.
      {% else %}
        build {{build.number}} failed. Fix me please.
      {% endif %}
   
trigger:
  branch:
  - master
  event:
  - push


