kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
 - name: prepare
   image: maven:3-jdk-8
   commands:
   - mvn --version
   - java -version
   
- name: test
  image: maven:3-jdk-8
  commands:
  - mvn test -B
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
 
