kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: maven:3-jdk-10
  commands:
  - mvn test -B
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
