---
kind: pipeline
name: info

steps:
 - name: prepare
   image: maven:3-jdk-8
   commands:
   - mvn --version
   - java -version
   
 gtalk:
  image: appleboy/drone-gtalk
  google_host: talk.google.com:443
  google_username: xxxxxxxxxx
  google_password: xxxxxxxxxx
  to: google_user_email_account
   
trigger:
  branch:
  - master
  event:
  - push


---
kind: pipeline
name: build

steps:
 - name: test
   image: maven:3-jdk-8
   commands:
   - mvn test -B
   - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

trigger:
  status:
  - success

depends_on:
- info
