---
kind: pipeline
name: info

steps:
 - name: prepare
   image: maven:3-jdk-8
   commands:
   - mvn --version
   - java -version
   
trigger:
  branch:
  - master
  event:
  - push

wechat:
  image: clem109/drone-wechat
  corpid: corpid
  corp_secret: secret
  agent_id: 1234567
  title: ${DRONE_REPO_NAME}
  description: "Build Number: ${DRONE_BUILD_NUMBER} failed. ${DRONE_COMMIT_AUTHOR} please fix. Check the results here: ${DRONE_BUILD_LINK} "
  msg_url: ${DRONE_BUILD_LINK}
  btn_txt: btn
  when:
    status: [ failure ]
